"""
etl/extract.py
--------------
Extraction layer for the FabLab ETL pipeline.

Supports two modes:
  - Mock mode (default): reads CSV files from data/raw/ generated by seed_data.py
  - Live mode          : reads from a Google Sheet via the Sheets API (requires
                         a service-account JSON at config/credentials.json and
                         GOOGLE_SHEET_ID set in .env)

The extract step performs minimal validation (file exists, expected columns
present) and returns raw DataFrames without any cleaning — that is the
transform step's responsibility.

Usage:
    from etl.extract import extract
    dfs = extract(mode="mock")   # or mode="live"
"""

import logging
from pathlib import Path
from typing import Literal

import pandas as pd
from typing import Dict, List, Optional

log = logging.getLogger(__name__)

# Expected columns for each sheet / CSV
EXPECTED_COLUMNS: Dict[str, List[str]] = {
    "instructors": ["instructor_id", "name", "email", "role", "specialization", "phone"],
    "classes": [
        "class_id",
        "class_name",
        "description",
        "age_group",
        "schedule_description",
        "is_recurring",
        "color",
        "instructor",
        "max_students",
    ],
    "registrations": [
        "student_name",
        "email",
        "phone",
        "parent_name",
        "class_id",
        "registration_date",
        "status",
    ],
    "material_usage": [
        "class_id",
        "instructor",
        "material_name",
        "quantity_used",
        "unit",
        "session_date",
        "notes",
    ],
}

# ── Mock mode ──────────────────────────────────────────────────────────────────


def _extract_mock(raw_dir: Path) -> Dict[str, pd.DataFrame]:
    """Read CSVs from data/raw/ and return raw DataFrames."""
    dfs: Dict[str, pd.DataFrame] = {}

    for name in EXPECTED_COLUMNS:
        csv_path = raw_dir / f"{name}.csv"
        if not csv_path.exists():
            raise FileNotFoundError(
                f"Raw data file not found: {csv_path}. "
                "Run `python etl/seed_data.py` first."
            )

        df = pd.read_csv(csv_path, dtype=str)  # read everything as strings initially
        df = df.fillna("")  # normalise NaN → empty string

        _validate_columns(name, df)
        log.info(
            "[extract] %-20s  %d rows  (source: %s)",
            name,
            len(df),
            csv_path.name,
        )
        dfs[name] = df

    return dfs


# ── Live mode (Google Sheets) ──────────────────────────────────────────────────


def _extract_live(credentials_path: str, sheet_id: str) -> Dict[str, pd.DataFrame]:
    """
    Read registration data from a Google Sheet.

    The sheet is expected to have one tab per data type:
      - "Instructors", "Classes", "Registrations", "Material Usage"

    To enable:
      1. Create a Google Cloud project and enable the Sheets API.
      2. Create a service account and download the JSON key to config/credentials.json.
      3. Share your Google Sheet with the service-account email (viewer access).
      4. Set GOOGLE_SHEET_ID in .env.
    """
    try:
        import gspread
        from oauth2client.service_account import ServiceAccountCredentials
    except ImportError as exc:
        raise ImportError(
            "gspread and oauth2client are required for live mode. "
            "Run: pip install gspread oauth2client"
        ) from exc

    scopes = [
        "https://spreadsheets.google.com/feeds",
        "https://www.googleapis.com/auth/drive",
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_name(credentials_path, scopes)
    client = gspread.authorize(creds)

    spreadsheet = client.open_by_key(sheet_id)

    tab_map = {
        "instructors": "Instructors",
        "classes": "Classes",
        "registrations": "Registrations",
        "material_usage": "Material Usage",
    }

    dfs: Dict[str, pd.DataFrame] = {}
    for name, tab_name in tab_map.items():
        worksheet = spreadsheet.worksheet(tab_name)
        records = worksheet.get_all_records()
        df = pd.DataFrame(records).astype(str).fillna("")
        _validate_columns(name, df)
        log.info("[extract] %-20s  %d rows  (source: Google Sheets tab '%s')", name, len(df), tab_name)
        dfs[name] = df

    return dfs


# ── Validation helper ──────────────────────────────────────────────────────────


def _validate_columns(name: str, df: pd.DataFrame) -> None:
    """Raise ValueError if any expected columns are missing."""
    missing = set(EXPECTED_COLUMNS[name]) - set(df.columns)
    if missing:
        raise ValueError(
            f"[extract] '{name}' is missing expected columns: {sorted(missing)}"
        )


# ── Public API ─────────────────────────────────────────────────────────────────


def extract(
    mode: Literal["mock", "live"] = "mock",
    raw_dir: Optional[Path] = None,
) -> Dict[str, pd.DataFrame]:
    """
    Extract raw data from the configured source.

    Args:
        mode:    "mock" reads from data/raw/ CSVs; "live" reads from Google Sheets.
        raw_dir: Override the raw data directory (used in tests).

    Returns:
        Dictionary mapping table name → raw DataFrame.
    """
    from config.settings import settings

    if raw_dir is None:
        raw_dir = settings.RAW_DATA_DIR

    log.info("[extract] Starting extraction  (mode=%s)", mode)

    if mode == "mock":
        dfs = _extract_mock(raw_dir)
    elif mode == "live":
        dfs = _extract_live(
            settings.GOOGLE_SHEETS_CREDENTIALS_PATH,
            settings.GOOGLE_SHEET_ID,
        )
    else:
        raise ValueError(f"Unknown extraction mode: {mode!r}")

    log.info("[extract] Extraction complete  (%d tables)", len(dfs))
    return dfs
